// <auto-generated />
namespace MOAS_LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedactivitytypesandchangedactivitytypepropinactivitymodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedactivitytypesandchangedactivitytypepropinactivitymodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201807191345050_Added-activitytypes-and-changed-activitytype-prop-in-activitymodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
